---
ReportDefinitions:
- reportName: HRMSEmployeewiseReport
  decryptionPathId: TradeLicenseDetailsReport_v2
  summary: HRMS Employeewise Report
  version: 1.0.0
  moduleName: rainmaker-hrms
  sourceColumns:
  - name: name
    label: reports.hrms.name
    type: string
    source: hrms
    total: false
  - name: mobilenumber
    label: reports.hrms.mobilenumber
    type: string
    source: hrms
    total: false
  - name: tenantid
    label: reports.hrms.tenantid
    type: string
    source: hrms
    total: false
  - name: role_assigned
    label: reports.hrms.role_assigned
    type: string
    source: hrms
    total: false
  - name: user_id
    label: reports.hrms.user_id
    type: string
    source: hrms
    total: false
  - name: departmentname
    label: report.hrms.departmentname
    type: string
    source: hrms
    total: false
  - name: designationname
    label: reports.hrms.designationname
    type: string
    source: hrms
    total: false
  - name: status
    label: reports.hrms.status
    type: string
    source: hrms
    total: false
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: pt
    wrapper: true
    isMandatory: false
    searchClause: AND u.tenantId = $ulb
  query: |
    with userroles as
    (
    select user_id,string_agg(role_code,',') as role_codes
    from eg_userrole_v1
    group by user_id
    )
    select   
    u.name, 
    u.mobilenumber,
    u.tenantid, 
    r.role_codes as role_assigned,
    e.code as user_id, 
    --assign.department,
    --assign.designation, 
    msg.message as departmentname,
    msg1.message as designationname,
    case
    when u.active='true' then 'Active'
    when u.active='false' then 'Inactive'
    end as status
    from eg_user u 
    Left Outer join userroles r on u.id=r.user_id inner join eg_hrms_employee e on u.id=e.id 
    Left Outer join eg_hrms_assignment assign on e.uuid=assign.employeeid and assign.iscurrentassignment='true'
    Left Outer join message as msg on msg.code=concat('COMMON_MASTERS_DEPARTMENT_',assign.department) and msg.locale='en_IN'
    Left Outer join message as msg1 on msg1.code=concat('COMMON_MASTERS_DESIGNATION_',assign.designation) and msg1.locale='en_IN'
    where u.type!='CITIZEN'
  orderby: ORDER BY u.tenantId asc
