serviceMaps:
  serviceName: update Escalation Status
  mappings:
  - version: 1.0
    description: Updates tl status for auto escalate
    fromTopic: tl-auto-escalation
    isTransaction: true
    queryMaps:

    - query: UPDATE eg_tl_tradelicense  SET applicationstatus=?, lastmodifiedby=?, lastmodifiedtime=? WHERE applicationnumber=? AND tenantId=?;
      basePath: ProcessInstances.*
      jsonMaps:
      - jsonPath: $.ProcessInstances.*.state.applicationStatus

      - jsonPath: $.ProcessInstances.*.auditDetails.lastModifiedBy

      - jsonPath: $.ProcessInstances.*.auditDetails.lastModifiedTime

      - jsonPath: $.ProcessInstances.*.businessId

      - jsonPath: $.ProcessInstances.*.tenantId
