serviceMaps:
  serviceName: collection-services-migration-count
  mappings:
  - version: 1.0
    description: Persists property details in egcl_payment_migration  table
    fromTopic: collection-migartion-batch-count
    isTransaction: true
    queryMaps:


    - query: INSERT INTO egcl_payment_migration (id,batch,batchsize,createdtime,tenantid,recordCount) VALUES (?,?,?,(SELECT extract(epoch from CURRENT_TIMESTAMP)*1000),?,?);
      basePath: MigrationCount
      jsonMaps:

      - jsonPath: $.MigrationCount.id

      - jsonPath: $.MigrationCount.offset

      - jsonPath: $.MigrationCount.limit

      - jsonPath: $.MigrationCount.tenantid

      - jsonPath: $.MigrationCount.recordCount