serviceMaps:
 serviceName: Bill Generate Scheduler Service
 mappings:
 - version: 1.0
   name: BillGenerateScheduler
   description: capture bill generation details for particular sewerage connection number
   fromTopic: save-sw-bill-scheduler
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_sw_scheduler (id, tenantid, transactiontype,locality,billingcyclestartdate,billingcycleenddate,status, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?,?,?,?,?);
      basePath: $.billScheduler
      jsonMaps:
       - jsonPath: $.billScheduler.id
       
       - jsonPath: $.billScheduler.tenantId
       
       - jsonPath: $.billScheduler.transactionType

       - jsonPath: $.billScheduler.locality
       
       - jsonPath: $.billScheduler.billingcycleStartdate

       - jsonPath: $.billScheduler.billingcycleEnddate

       - jsonPath: $.billScheduler.status
       
       - jsonPath: $.billScheduler.auditDetails.createdBy

       - jsonPath: $.billScheduler.auditDetails.lastModifiedBy

       - jsonPath: $.billScheduler.auditDetails.createdTime

       - jsonPath: $.billScheduler.auditDetails.lastModifiedTime