--- 
ServiceMaps: 
  mappings: 
    - 
      configKey: INDEX
      indexes: 
        - 
          customJsonMapping: 
            externalUriMapping: 
              - 
                apiRequest: 
                  RequestInfo: 
                    action: asd
                    apiId: org.egov.pt
                    authToken: 02dbe5be-28df-4d82-954f-3d27c56cca7d
                    did: "4354648646"
                    key: xyz
                    msgId: "654654"
                    requesterId: "61"
                    ts: 1502890899493
                    userInfo: 
                      id: 73
                    ver: "1.0"
                path: "http://egov-location:8080/egov-location/location/v11/boundarys/_search"
                queryParam: "hierarchyTypeCode=REVENUE,boundaryType=Block,codes=$.address.locality.code,tenantId=$.tenantId"
                uriResponseMapping: 
                  - 
                    inJsonPath: "$.TenantBoundary[0].boundary[0]"
                    outJsonPath: $.Data.ward
            fieldMapping: 
              - 
                inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - 
                inJsonPath: $.id
                outJsonPath: $.Data.id
              - 
                inJsonPath: $.transactionNumber
                outJsonPath: $.Data.transactionNumber
              - 
                inJsonPath: $.transactionDate
                outJsonPath: $.Data.transactionDate
              - 
                inJsonPath: $.paymentMode
                outJsonPath: $.Data.paymentMode
              - 
                inJsonPath: $.paymentStatus
                outJsonPath: $.Data.paymentStatus
              - 
                inJsonPath: $.payerId
                outJsonPath: $.Data.payer.id
              - 
                inJsonPath: $.payerName
                outJsonPath: $.Data.payer.name
              - 
                inJsonPath: $.paidBy
                outJsonPath: $.Data.paidBy
              - 
                inJsonPath: $.paymentDetails
                outJsonPath: $.Data.paymentDetails
              - 
                inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - 
                inJsonPath: $.additionalDetails
                outJsonPath: $.Data.additionalDetails
              - 
                inJsonPath: $.@timestamp
                outJsonPath: $.Data.@timestamp
            indexMapping: 
              Data: 
                ? "@timestamp"
                : timestamp
                additionalDetails: {}
                auditDetails: {}
                id: ""
                paidBy: ""
                payer: 
                  id: ""
                  name: ""
                paymentDetails: {}
                paymentMode: ""
                paymentStatus: ""
                tenantData: {}
                tenantId: ""
                transactionDate: 1
                transactionNumber: ""
                ward: {}
            mdmsMapping: 
              - 
                filter: "[?(@.code == $tenant)]"
                filterMapping: 
                  - 
                    valueJsonpath: $.tenantId
                    variable: $tenant
                masterName: tenants
                moduleName: tenant
                path: "http://egov-mdms-service:8080/egov-mdms-service/v1/_search"
                tenantId: pb
                uriResponseMapping: 
                  - 
                    inJsonPath: $.MdmsRes.tenant.tenants
                    outJsonPath: $.Data.tenantData
          id: $.id
          isBulk: false
          jsonPath: $.Payment
          name: paymentsindex-v1
          timeStampField: $.auditDetails.createdTime
          type: payments
      topic: egov.collection.payment-create
    - 
      configKey: INDEX
      indexes: 
        - 
          customJsonMapping: 
            externalUriMapping: 
              - 
                apiRequest: 
                  RequestInfo: 
                    action: asd
                    apiId: org.egov.pt
                    authToken: 02dbe5be-28df-4d82-954f-3d27c56cca7d
                    did: "4354648646"
                    key: xyz
                    msgId: "654654"
                    requesterId: "61"
                    ts: 1502890899493
                    userInfo: 
                      id: 73
                    ver: "1.0"
                path: "http://egov-location:8080/egov-location/location/v11/boundarys/_search"
                queryParam: "hierarchyTypeCode=REVENUE,boundaryType=Block,codes=$.address.locality.code,tenantId=$.tenantId"
                uriResponseMapping: 
                  - 
                    inJsonPath: "$.TenantBoundary[0].boundary[0]"
                    outJsonPath: $.Data.ward
            fieldMapping: 
              - 
                inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - 
                inJsonPath: $.id
                outJsonPath: $.Data.id
              - 
                inJsonPath: $.transactionNumber
                outJsonPath: $.Data.transactionNumber
              - 
                inJsonPath: $.transactionDate
                outJsonPath: $.Data.transactionDate
              - 
                inJsonPath: $.paymentMode
                outJsonPath: $.Data.paymentMode
              - 
                inJsonPath: $.paymentStatus
                outJsonPath: $.Data.paymentStatus
              - 
                inJsonPath: $.payerId
                outJsonPath: $.Data.payer.id
              - 
                inJsonPath: $.payerName
                outJsonPath: $.Data.payer.name
              - 
                inJsonPath: $.paidBy
                outJsonPath: $.Data.paidBy
              - 
                inJsonPath: $.paymentDetails
                outJsonPath: $.Data.paymentDetails
              - 
                inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - 
                inJsonPath: $.additionalDetails
                outJsonPath: $.Data.additionalDetails
              - 
                inJsonPath: $.@timestamp
                outJsonPath: $.Data.@timestamp
            indexMapping: 
              Data: 
                ? "@timestamp"
                : timestamp
                additionalDetails: {}
                auditDetails: {}
                id: ""
                paidBy: ""
                payer: 
                  id: ""
                  name: ""
                paymentDetails: {}
                paymentMode: ""
                paymentStatus: ""
                tenantData: {}
                tenantId: ""
                transactionDate: 1
                transactionNumber: ""
                ward: {}
            mdmsMapping: 
              - 
                filter: "[?(@.code == $tenant)]"
                filterMapping: 
                  - 
                    valueJsonpath: $.tenantId
                    variable: $tenant
                masterName: tenants
                moduleName: tenant
                path: "http://egov-mdms-service:8080/egov-mdms-service/v1/_search"
                tenantId: pb
                uriResponseMapping: 
                  - 
                    inJsonPath: $.MdmsRes.tenant.tenants
                    outJsonPath: $.Data.tenantData
          id: $.id
          isBulk: false
          jsonPath: $.Payment
          name: paymentsindex-v1
          timeStampField: $.auditDetails.createdTime
          type: payments
      topic: egov.collection.payment-update
    - 
      configKey: LEGACYINDEX
      indexes: 
        - 
          customJsonMapping: 
            externalUriMapping: 
              - 
                apiRequest: 
                  RequestInfo: 
                    action: asd
                    apiId: org.egov.pt
                    authToken: 02dbe5be-28df-4d82-954f-3d27c56cca7d
                    did: "4354648646"
                    key: xyz
                    msgId: "654654"
                    requesterId: "61"
                    ts: 1502890899493
                    userInfo: 
                      id: 73
                    ver: "1.0"
                path: "http://egov-location:8080/egov-location/location/v11/boundarys/_search"
                queryParam: "hierarchyTypeCode=REVENUE,boundaryType=Block,codes=$.address.locality.code,tenantId=$.tenantId"
                uriResponseMapping: 
                  - 
                    inJsonPath: "$.TenantBoundary[0].boundary[0]"
                    outJsonPath: $.Data.ward
            fieldMapping: 
              - 
                inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - 
                inJsonPath: $.id
                outJsonPath: $.Data.id
              - 
                inJsonPath: $.transactionNumber
                outJsonPath: $.Data.transactionNumber
              - 
                inJsonPath: $.transactionDate
                outJsonPath: $.Data.transactionDate
              - 
                inJsonPath: $.paymentMode
                outJsonPath: $.Data.paymentMode
              - 
                inJsonPath: $.paymentStatus
                outJsonPath: $.Data.paymentStatus
              - 
                inJsonPath: $.payerId
                outJsonPath: $.Data.payer.id
              - 
                inJsonPath: $.payerName
                outJsonPath: $.Data.payer.name
              - 
                inJsonPath: $.paidBy
                outJsonPath: $.Data.paidBy
              - 
                inJsonPath: $.paymentDetails
                outJsonPath: $.Data.paymentDetails
              - 
                inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - 
                inJsonPath: $.additionalDetails
                outJsonPath: $.Data.additionalDetails
              - 
                inJsonPath: $.@timestamp
                outJsonPath: $.Data.@timestamp
            indexMapping: 
              Data: 
                ? "@timestamp"
                : timestamp
                additionalDetails: {}
                auditDetails: {}
                id: ""
                paidBy: ""
                payer: 
                  id: ""
                  name: ""
                paymentDetails: {}
                paymentMode: ""
                paymentStatus: ""
                tenantData: {}
                tenantId: ""
                transactionDate: 1
                transactionNumber: ""
                ward: {}
            mdmsMapping: 
              - 
                filter: "[?(@.code == $tenant)]"
                filterMapping: 
                  - 
                    valueJsonpath: $.tenantId
                    variable: $tenant
                masterName: tenants
                moduleName: tenant
                path: "http://egov-mdms-service:8080/egov-mdms-service/v1/_search"
                tenantId: pb
                uriResponseMapping: 
                  - 
                    inJsonPath: $.MdmsRes.tenant.tenants
                    outJsonPath: $.Data.tenantData
          id: $.id
          isBulk: true
          jsonPath: $.Payments.*
          name: paymentsindex-v1
          timeStampField: $.auditDetails.createdTime
          type: payments
      topic: egov-payment-legacy-index
    - 
      configKey: INDEX
      indexes: 
        - 
          customJsonMapping: 
            externalUriMapping: 
              - 
                apiRequest: 
                  RequestInfo: 
                    action: asd
                    apiId: org.egov.pt
                    authToken: 02dbe5be-28df-4d82-954f-3d27c56cca7d
                    did: "4354648646"
                    key: xyz
                    msgId: "654654"
                    requesterId: "61"
                    ts: 1502890899493
                    userInfo: 
                      id: 73
                    ver: "1.0"
                path: "http://egov-location:8080/egov-location/location/v11/boundarys/_search"
                queryParam: "hierarchyTypeCode=REVENUE,boundaryType=Block,codes=$.address.locality.code,tenantId=$.tenantId"
                uriResponseMapping: 
                  - 
                    inJsonPath: "$.TenantBoundary[0].boundary[0]"
                    outJsonPath: $.Data.ward
            fieldMapping: 
              - 
                inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - 
                inJsonPath: $.id
                outJsonPath: $.Data.id
              - 
                inJsonPath: $.transactionNumber
                outJsonPath: $.Data.transactionNumber
              - 
                inJsonPath: $.transactionDate
                outJsonPath: $.Data.transactionDate
              - 
                inJsonPath: $.paymentMode
                outJsonPath: $.Data.paymentMode
              - 
                inJsonPath: $.paymentStatus
                outJsonPath: $.Data.paymentStatus
              - 
                inJsonPath: $.payerId
                outJsonPath: $.Data.payer.id
              - 
                inJsonPath: $.payerName
                outJsonPath: $.Data.payer.name
              - 
                inJsonPath: $.paidBy
                outJsonPath: $.Data.paidBy
              - 
                inJsonPath: $.paymentDetails
                outJsonPath: $.Data.paymentDetails
              - 
                inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - 
                inJsonPath: $.additionalDetails
                outJsonPath: $.Data.additionalDetails
              - 
                inJsonPath: $.@timestamp
                outJsonPath: $.Data.@timestamp
            indexMapping: 
              Data: 
                ? "@timestamp"
                : timestamp
                additionalDetails: {}
                auditDetails: {}
                id: ""
                paidBy: ""
                payer: 
                  id: ""
                  name: ""
                paymentDetails: {}
                paymentMode: ""
                paymentStatus: ""
                tenantData: {}
                tenantId: ""
                transactionDate: 1
                transactionNumber: ""
                ward: {}
            mdmsMapping: 
              - 
                filter: "[?(@.code == $tenant)]"
                filterMapping: 
                  - 
                    valueJsonpath: $.tenantId
                    variable: $tenant
                masterName: tenants
                moduleName: tenant
                path: "http://egov-mdms-service:8080/egov-mdms-service/v1/_search"
                tenantId: pb
                uriResponseMapping: 
                  - 
                    inJsonPath: $.MdmsRes.tenant.tenants
                    outJsonPath: $.Data.tenantData
          id: $.id
          isBulk: false
          jsonPath: $.Payment
          name: paymentsindex-v1
          timeStampField: $.auditDetails.createdTime
          type: payments
      topic: egov.collection.payment-cancel
  serviceName: "Collection Services"
  version: "1.0.0"
